language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
    - sudo apt-get install -y --force-yes libgeoip-dev
    - pecl install geoip
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction

script: phpunit --coverage-text
