layouts: ./geocoder-php.github.io/_layouts/

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

name:        Geocoder
description: The almost missing Geocoder PHP library!
url:         http://geocoder-php.org/

travis_base_url: https://travis-ci.org/geocoder-php/
github_base_url: https://github.com/geocoder-php/
